using System.Text.Json.Serialization;

namespace CSM.DataAccess.BeatSaver
{
    [JsonConverter(typeof(JsonStringEnumConverter))]
    internal enum Environment
    {
        None,
        All,
        [JsonStringEnumMemberName("DefaultEnvironment")]
        DefaultEnvironment,
        [JsonStringEnumMemberName("TriangleEnvironment")]
        TriangleEnvironment,
        [JsonStringEnumMemberName("NiceEnvironment")]
        NiceEnvironment,
        [JsonStringEnumMemberName("BigMirrorEnvironment")]
        BigMirrorEnvironment,
        [JsonStringEnumMemberName("KDAEnvironment")]
        KDAEnvironment,
        [JsonStringEnumMemberName("MonstercatEnvironment")]
        MonstercatEnvironment,
        [JsonStringEnumMemberName("CrabRaveEnvironment")]
        CrabRaveEnvironment,
        [JsonStringEnumMemberName("DragonsEnvironment")]
        DragonsEnvironment,
        [JsonStringEnumMemberName("OriginsEnvironment")]
        OriginsEnvironment,
        [JsonStringEnumMemberName("PanicEnvironment")]
        PanicEnvironment,
        [JsonStringEnumMemberName("RocketEnvironment")]
        RocketEnvironment,
        [JsonStringEnumMemberName("GreenDayEnvironment")]
        GreenDayEnvironment,
        [JsonStringEnumMemberName("GreenDayGrenadeEnvironment")]
        GreenDayGrenadeEnvironment,
        [JsonStringEnumMemberName("TimbalandEnvironment")]
        TimbalandEnvironment,
        [JsonStringEnumMemberName("FitBeatEnvironment")]
        FitBeatEnvironment,
        [JsonStringEnumMemberName("LinkinParkEnvironment")]
        LinkinParkEnvironment,
        [JsonStringEnumMemberName("BTSEnvironment")]
        BTSEnvironment,
        [JsonStringEnumMemberName("KaleidoscopeEnvironment")]
        KaleidoscopeEnvironment,
        [JsonStringEnumMemberName("InterscopeEnvironment")]
        InterscopeEnvironment,
        [JsonStringEnumMemberName("SkrillexEnvironment")]
        SkrillexEnvironment,
        [JsonStringEnumMemberName("BillieEnvironment")]
        BillieEnvironment,
        [JsonStringEnumMemberName("HalloweenEnvironment")]
        HalloweenEnvironment,
        [JsonStringEnumMemberName("GagaEnvironment")]
        GagaEnvironment,
        [JsonStringEnumMemberName("GlassDesertEnvironment")]
        GlassDesertEnvironment,
        [JsonStringEnumMemberName("MultiplayerEnvironment")]
        MultiplayerEnvironment,
        [JsonStringEnumMemberName("WeaveEnvironment")]
        WeaveEnvironment,
        [JsonStringEnumMemberName("PyroEnvironment")]
        PyroEnvironment,
        [JsonStringEnumMemberName("EDMEnvironment")]
        EDMEnvironment,
        [JsonStringEnumMemberName("TheSecondEnvironment")]
        TheSecondEnvironment,
        [JsonStringEnumMemberName("LizzoEnvironment")]
        LizzoEnvironment,
        [JsonStringEnumMemberName("TheWeekndEnvironment")]
        TheWeekndEnvironment,
        [JsonStringEnumMemberName("RockMixtapeEnvironment")]
        RockMixtapeEnvironment,
        [JsonStringEnumMemberName("Dragons2Environment")]
        Dragons2Environment,
        [JsonStringEnumMemberName("Panic2Environment")]
        Panic2Environment,
        [JsonStringEnumMemberName("QueenEnvironment")]
        QueenEnvironment,
        [JsonStringEnumMemberName("LinkinPark2Environment")]
        LinkinPark2Environment,
        [JsonStringEnumMemberName("TheRollingStonesEnvironment")]
        TheRollingStonesEnvironment,
        [JsonStringEnumMemberName("LatticeEnvironment")]
        LatticeEnvironment,
        [JsonStringEnumMemberName("DaftPunkEnvironment")]
        DaftPunkEnvironment,
        [JsonStringEnumMemberName("HipHopEnvironment")]
        HipHopEnvironment,
        [JsonStringEnumMemberName("ColliderEnvironment")]
        ColliderEnvironment,
        [JsonStringEnumMemberName("BritneyEnvironment")]
        BritneyEnvironment,
        [JsonStringEnumMemberName("Monstercat2Environment")]
        Monstercat2Environment,
        [JsonStringEnumMemberName("MetallicaEnvironment")]
        MetallicaEnvironment
    }
}
