using System.Text.Json.Serialization;

namespace CSM.DataAccess.BeatSaver
{
    [JsonConverter(typeof(JsonStringEnumConverter))]
    internal enum Tag
    {
        [JsonStringEnumMemberName("tech")]
        Tech,
        [JsonStringEnumMemberName("dance-style")]
        DanceStyle,
        [JsonStringEnumMemberName("speed")]
        Speed,
        [JsonStringEnumMemberName("balanced")]
        Balanced,
        [JsonStringEnumMemberName("challenge")]
        Challenge,
        [JsonStringEnumMemberName("accuracy")]
        Accuracy,
        [JsonStringEnumMemberName("fitness")]
        Fitness,
        [JsonStringEnumMemberName("swing")]
        Swing,
        [JsonStringEnumMemberName("nightcore")]
        Nightcore,
        [JsonStringEnumMemberName("folk-acoustic")]
        FolkAccoustic,
        [JsonStringEnumMemberName("kids-family")]
        KidsFamily,
        [JsonStringEnumMemberName("ambient")]
        Ambient,
        [JsonStringEnumMemberName("funk-disco")]
        FunkDisco,
        [JsonStringEnumMemberName("jazz")]
        Jazz,
        [JsonStringEnumMemberName("classical-orchestral")]
        ClassicalOrchestral,
        [JsonStringEnumMemberName("soul")]
        Soul,
        [JsonStringEnumMemberName("speedcore")]
        Speedcore,
        [JsonStringEnumMemberName("punk")]
        Punk,
        [JsonStringEnumMemberName("rb")]
        Rb,
        [JsonStringEnumMemberName("holiday")]
        Holiday,
        [JsonStringEnumMemberName("vocaloid")]
        Vocaloid,
        [JsonStringEnumMemberName("j-rock")]
        JRock,
        [JsonStringEnumMemberName("trance")]
        Trance,
        [JsonStringEnumMemberName("drum-and-bass")]
        DrumAndBass,
        [JsonStringEnumMemberName("comedy-meme")]
        ComedyMeme,
        [JsonStringEnumMemberName("instrumental")]
        Instrumental,
        [JsonStringEnumMemberName("hardcore")]
        Hardcore,
        [JsonStringEnumMemberName("k-pop")]
        KPop,
        [JsonStringEnumMemberName("indie")]
        Indie,
        [JsonStringEnumMemberName("techno")]
        Techno,
        [JsonStringEnumMemberName("house")]
        House,
        [JsonStringEnumMemberName("video-game-soundtrack")]
        VideoGameSoundtrack,
        [JsonStringEnumMemberName("tv-movie-soundtrack")]
        TvMovieSoundtrack,
        [JsonStringEnumMemberName("alternative")]
        Alternative,
        [JsonStringEnumMemberName("dubstep")]
        Dubstep,
        [JsonStringEnumMemberName("metal")]
        Metal,
        [JsonStringEnumMemberName("anime")]
        Anime,
        [JsonStringEnumMemberName("hip-hop-rap")]
        HipHopRap,
        [JsonStringEnumMemberName("j-pop")]
        JPop,
        [JsonStringEnumMemberName("dance")]
        Dance,
        [JsonStringEnumMemberName("rock")]
        Rock,
        [JsonStringEnumMemberName("pop")]
        Pop,
        [JsonStringEnumMemberName("electronic")]
        Electronic,
    }
}
