//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSM.UiLogic.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSM.UiLogic.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete custom level.
        /// </summary>
        public static string CustomLevels_Delete_Caption {
            get {
                return ResourceManager.GetString("CustomLevels_Delete_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete the selected custom level?.
        /// </summary>
        public static string CustomLevels_Delete_Content {
            get {
                return ResourceManager.GetString("CustomLevels_Delete_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} custom levels loaded.
        /// </summary>
        public static string CustomLevels_MultipleCustomLevelsLoaded {
            get {
                return ResourceManager.GetString("CustomLevels_MultipleCustomLevelsLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No custom levels loaded.
        /// </summary>
        public static string CustomLevels_NoCustomLevelsLoaded {
            get {
                return ResourceManager.GetString("CustomLevels_NoCustomLevelsLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 custom level loaded.
        /// </summary>
        public static string CustomLevels_OneCustomLevelLoaded {
            get {
                return ResourceManager.GetString("CustomLevels_OneCustomLevelLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete playlist.
        /// </summary>
        public static string Playlists_DeletePlaylist_Caption {
            get {
                return ResourceManager.GetString("Playlists_DeletePlaylist_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete the selected playlist?.
        /// </summary>
        public static string Playlists_DeletePlaylist_Content {
            get {
                return ResourceManager.GetString("Playlists_DeletePlaylist_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete folder.
        /// </summary>
        public static string Playlists_DeletePlaylistFolder_Caption {
            get {
                return ResourceManager.GetString("Playlists_DeletePlaylistFolder_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete the selected folder? All playlists within this folder will be deleted too!.
        /// </summary>
        public static string Playlists_DeletePlaylistFolder_Content {
            get {
                return ResourceManager.GetString("Playlists_DeletePlaylistFolder_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NA (Try to use Tools to fix this issue).
        /// </summary>
        public static string Playlists_SongName_NA {
            get {
                return ResourceManager.GetString("Playlists_SongName_NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open file dialog.
        /// </summary>
        public static string Settings_BeatSaber_FileDialog {
            get {
                return ResourceManager.GetString("Settings_BeatSaber_FileDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong path.
        /// </summary>
        public static string Settings_BeatSaber_ValidatePath_Caption {
            get {
                return ResourceManager.GetString("Settings_BeatSaber_ValidatePath_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path does not exist. Please enter a new path.
        /// </summary>
        public static string Settings_BeatSaber_ValidatePath_Content {
            get {
                return ResourceManager.GetString("Settings_BeatSaber_ValidatePath_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Levels.
        /// </summary>
        public static string Workspace_CustomLevels {
            get {
                return ResourceManager.GetString("Workspace_CustomLevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlists.
        /// </summary>
        public static string Workspace_Playlists {
            get {
                return ResourceManager.GetString("Workspace_Playlists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string Workspace_Tools {
            get {
                return ResourceManager.GetString("Workspace_Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitch.
        /// </summary>
        public static string Workspace_Twitch {
            get {
                return ResourceManager.GetString("Workspace_Twitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
