<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>2.1.0</Version>
    <Copyright>Copyright 2026 InnocentThief</Copyright>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CSM.Framework\CSM.Framework.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="CSM" />
    <internalsVisibleTo Include="CSM.UiLogic" />
    <internalsVisibleTo Include="CSM.Business" />
  </ItemGroup>

</Project>
