<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>2.1.0</Version>
    <Copyright>Copyright 2026 InnocentThief</Copyright>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Logging\**" />
    <EmbeddedResource Remove="Logging\**" />
    <None Remove="Logging\**" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="CSM" />
    <InternalsVisibleTo Include="CSM.Business" />
    <InternalsVisibleTo Include="CSM.UiLogic" />
  </ItemGroup>

</Project>
