//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSM.App.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSM.App.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Development.
        /// </summary>
        public static string About_Development {
            get {
                return ResourceManager.GetString("About_Development", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon.
        /// </summary>
        public static string About_Icon {
            get {
                return ResourceManager.GetString("About_Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idea.
        /// </summary>
        public static string About_Idea {
            get {
                return ResourceManager.GetString("About_Idea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing.
        /// </summary>
        public static string About_Testing {
            get {
                return ResourceManager.GetString("About_Testing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No custom level selected.
        /// </summary>
        public static string CustomLevels_Detail_NoData {
            get {
                return ResourceManager.GetString("CustomLevels_Detail_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string MainWindow_About {
            get {
                return ResourceManager.GetString("MainWindow_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string MainWindow_Settings {
            get {
                return ResourceManager.GetString("MainWindow_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No song selected.
        /// </summary>
        public static string Playlist_Detail_NoData {
            get {
                return ResourceManager.GetString("Playlist_Detail_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No playlist selected.
        /// </summary>
        public static string Playlist_NoData {
            get {
                return ResourceManager.GetString("Playlist_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist.
        /// </summary>
        public static string Playlist_Title {
            get {
                return ResourceManager.GetString("Playlist_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string Playlists_Author {
            get {
                return ResourceManager.GetString("Playlists_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Custom Levels / Beat Saber Favorites / Song Search.
        /// </summary>
        public static string Playlists_AvailableCustomLevels_Title {
            get {
                return ResourceManager.GetString("Playlists_AvailableCustomLevels_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletes the selected playlist / folder.
        /// </summary>
        public static string Playlists_Delete {
            get {
                return ResourceManager.GetString("Playlists_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Playlists_Description {
            get {
                return ResourceManager.GetString("Playlists_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Playlists_Name {
            get {
                return ResourceManager.GetString("Playlists_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh the playlists.
        /// </summary>
        public static string Playlists_Refresh {
            get {
                return ResourceManager.GetString("Playlists_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Levels Path.
        /// </summary>
        public static string Settings_BeatSaber_CustomLevelsPath {
            get {
                return ResourceManager.GetString("Settings_BeatSaber_CustomLevelsPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beat Saber Install Path.
        /// </summary>
        public static string Settings_BeatSaber_InstallPath {
            get {
                return ResourceManager.GetString("Settings_BeatSaber_InstallPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlists Path.
        /// </summary>
        public static string Settings_BeatSaber_PlaylistsPath {
            get {
                return ResourceManager.GetString("Settings_BeatSaber_PlaylistsPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beat Saber.
        /// </summary>
        public static string Settings_BeatSaber_Title {
            get {
                return ResourceManager.GetString("Settings_BeatSaber_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Endpoint.
        /// </summary>
        public static string Settings_BeatSaver_Endpoint {
            get {
                return ResourceManager.GetString("Settings_BeatSaver_Endpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart needed if changed. Clear to set to default..
        /// </summary>
        public static string Settings_BeatSaver_Endpoint_ToolTip {
            get {
                return ResourceManager.GetString("Settings_BeatSaver_Endpoint_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closes Settings.
        /// </summary>
        public static string Settings_Close {
            get {
                return ResourceManager.GetString("Settings_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Levels.
        /// </summary>
        public static string Settings_Workspace_CustomLevels {
            get {
                return ResourceManager.GetString("Settings_Workspace_CustomLevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove song after adding to playlist.
        /// </summary>
        public static string Settings_Workspace_RemoveSongAfterAddingToPlaylist {
            get {
                return ResourceManager.GetString("Settings_Workspace_RemoveSongAfterAddingToPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song Detail Position.
        /// </summary>
        public static string Settings_Workspace_SongDetailPosition {
            get {
                return ResourceManager.GetString("Settings_Workspace_SongDetailPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom.
        /// </summary>
        public static string Settings_Workspace_SongDetailPosition_Bottom {
            get {
                return ResourceManager.GetString("Settings_Workspace_SongDetailPosition_Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        public static string Settings_Workspace_SongDetailPosition_Right {
            get {
                return ResourceManager.GetString("Settings_Workspace_SongDetailPosition_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Workspace.
        /// </summary>
        public static string Settings_Workspaces_Default {
            get {
                return ResourceManager.GetString("Settings_Workspaces_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workspaces.
        /// </summary>
        public static string Settings_Workspaces_Title {
            get {
                return ResourceManager.GetString("Settings_Workspaces_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        public static string SongSearch_ColumnHeader_Rating {
            get {
                return ResourceManager.GetString("SongSearch_ColumnHeader_Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clears all filters.
        /// </summary>
        public static string SongSearch_Search_ClearFilter {
            get {
                return ResourceManager.GetString("SongSearch_Search_ClearFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enhanced Search.
        /// </summary>
        public static string SongSearch_Search_Enhanced {
            get {
                return ResourceManager.GetString("SongSearch_Search_Enhanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string SongSearch_Search_General {
            get {
                return ResourceManager.GetString("SongSearch_Search_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI.
        /// </summary>
        public static string SongSearch_Search_General_AI {
            get {
                return ResourceManager.GetString("SongSearch_Search_General_AI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curated.
        /// </summary>
        public static string SongSearch_Search_General_Curated {
            get {
                return ResourceManager.GetString("SongSearch_Search_General_Curated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Spread.
        /// </summary>
        public static string SongSearch_Search_General_FullSpread {
            get {
                return ResourceManager.GetString("SongSearch_Search_General_FullSpread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranked.
        /// </summary>
        public static string SongSearch_Search_General_Ranked {
            get {
                return ResourceManager.GetString("SongSearch_Search_General_Ranked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verified Mapper.
        /// </summary>
        public static string SongSearch_Search_General_Verified {
            get {
                return ResourceManager.GetString("SongSearch_Search_General_Verified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relevance.
        /// </summary>
        public static string SongSearch_Search_Relevance {
            get {
                return ResourceManager.GetString("SongSearch_Search_Relevance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curated.
        /// </summary>
        public static string SongSearch_Search_Relevance_Curated {
            get {
                return ResourceManager.GetString("SongSearch_Search_Relevance_Curated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest.
        /// </summary>
        public static string SongSearch_Search_Relevance_Latest {
            get {
                return ResourceManager.GetString("SongSearch_Search_Relevance_Latest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        public static string SongSearch_Search_Relevance_Rating {
            get {
                return ResourceManager.GetString("SongSearch_Search_Relevance_Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relevance.
        /// </summary>
        public static string SongSearch_Search_Relevance_Relevance {
            get {
                return ResourceManager.GetString("SongSearch_Search_Relevance_Relevance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requirements.
        /// </summary>
        public static string SongSearch_Search_Requirements {
            get {
                return ResourceManager.GetString("SongSearch_Search_Requirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chroma.
        /// </summary>
        public static string SongSearch_Search_Requirements_Chroma {
            get {
                return ResourceManager.GetString("SongSearch_Search_Requirements_Chroma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cinema.
        /// </summary>
        public static string SongSearch_Search_Requirements_Cinema {
            get {
                return ResourceManager.GetString("SongSearch_Search_Requirements_Cinema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapping Extensions.
        /// </summary>
        public static string SongSearch_Search_Requirements_ME {
            get {
                return ResourceManager.GetString("SongSearch_Search_Requirements_ME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noodle.
        /// </summary>
        public static string SongSearch_Search_Requirements_Noodle {
            get {
                return ResourceManager.GetString("SongSearch_Search_Requirements_Noodle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows more results.
        /// </summary>
        public static string SongSearch_Search_ShowMeMore_ToolTip {
            get {
                return ResourceManager.GetString("SongSearch_Search_ShowMeMore_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags (Map-Style).
        /// </summary>
        public static string SongSearch_Search_Tags_MapStyle {
            get {
                return ResourceManager.GetString("SongSearch_Search_Tags_MapStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accuracy.
        /// </summary>
        public static string SongSearch_Search_Tags_MapStyle_Accuracy {
            get {
                return ResourceManager.GetString("SongSearch_Search_Tags_MapStyle_Accuracy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balanced.
        /// </summary>
        public static string SongSearch_Search_Tags_MapStyle_Balanced {
            get {
                return ResourceManager.GetString("SongSearch_Search_Tags_MapStyle_Balanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenge.
        /// </summary>
        public static string SongSearch_Search_Tags_MapStyle_Challenge {
            get {
                return ResourceManager.GetString("SongSearch_Search_Tags_MapStyle_Challenge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dance.
        /// </summary>
        public static string SongSearch_Search_Tags_MapStyle_Dance {
            get {
                return ResourceManager.GetString("SongSearch_Search_Tags_MapStyle_Dance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fitness.
        /// </summary>
        public static string SongSearch_Search_Tags_MapStyle_Fitness {
            get {
                return ResourceManager.GetString("SongSearch_Search_Tags_MapStyle_Fitness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string SongSearch_Search_Tags_MapStyle_None {
            get {
                return ResourceManager.GetString("SongSearch_Search_Tags_MapStyle_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        public static string SongSearch_Search_Tags_MapStyle_Speed {
            get {
                return ResourceManager.GetString("SongSearch_Search_Tags_MapStyle_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tech.
        /// </summary>
        public static string SongSearch_Search_Tags_MapStyle_Tech {
            get {
                return ResourceManager.GetString("SongSearch_Search_Tags_MapStyle_Tech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags (Song-Style).
        /// </summary>
        public static string SongSearch_Search_Tags_SongStyle {
            get {
                return ResourceManager.GetString("SongSearch_Search_Tags_SongStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternative.
        /// </summary>
        public static string SongSearch_Search_Tags_SongStyle_Alternative {
            get {
                return ResourceManager.GetString("SongSearch_Search_Tags_SongStyle_Alternative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ambient.
        /// </summary>
        public static string SongSearch_Search_Tags_SongStyle_Ambient {
            get {
                return ResourceManager.GetString("SongSearch_Search_Tags_SongStyle_Ambient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anime.
        /// </summary>
        public static string SongSearch_Search_Tags_SongStyle_Anime {
            get {
                return ResourceManager.GetString("SongSearch_Search_Tags_SongStyle_Anime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comedy &amp; Meme.
        /// </summary>
        public static string SongSearch_Search_Tags_SongStyle_ComedyMeme {
            get {
                return ResourceManager.GetString("SongSearch_Search_Tags_SongStyle_ComedyMeme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dance.
        /// </summary>
        public static string SongSearch_Search_Tags_SongStyle_Dance {
            get {
                return ResourceManager.GetString("SongSearch_Search_Tags_SongStyle_Dance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drum and Bass.
        /// </summary>
        public static string SongSearch_Search_Tags_SongStyle_DrumAndBass {
            get {
                return ResourceManager.GetString("SongSearch_Search_Tags_SongStyle_DrumAndBass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dubstep.
        /// </summary>
        public static string SongSearch_Search_Tags_SongStyle_Dubstep {
            get {
                return ResourceManager.GetString("SongSearch_Search_Tags_SongStyle_Dubstep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electronic.
        /// </summary>
        public static string SongSearch_Search_Tags_SongStyle_Electronic {
            get {
                return ResourceManager.GetString("SongSearch_Search_Tags_SongStyle_Electronic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folk &amp; Acoustic.
        /// </summary>
        public static string SongSearch_Search_Tags_SongStyle_FoldAcoustic {
            get {
                return ResourceManager.GetString("SongSearch_Search_Tags_SongStyle_FoldAcoustic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funk &amp; Disco.
        /// </summary>
        public static string SongSearch_Search_Tags_SongStyle_FunkDisco {
            get {
                return ResourceManager.GetString("SongSearch_Search_Tags_SongStyle_FunkDisco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardcore.
        /// </summary>
        public static string SongSearch_Search_Tags_SongStyle_Hardcore {
            get {
                return ResourceManager.GetString("SongSearch_Search_Tags_SongStyle_Hardcore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holiday.
        /// </summary>
        public static string SongSearch_Search_Tags_SongStyle_Holiday {
            get {
                return ResourceManager.GetString("SongSearch_Search_Tags_SongStyle_Holiday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to House.
        /// </summary>
        public static string SongSearch_Search_Tags_SongStyle_House {
            get {
                return ResourceManager.GetString("SongSearch_Search_Tags_SongStyle_House", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indie.
        /// </summary>
        public static string SongSearch_Search_Tags_SongStyle_Indie {
            get {
                return ResourceManager.GetString("SongSearch_Search_Tags_SongStyle_Indie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrumental.
        /// </summary>
        public static string SongSearch_Search_Tags_SongStyle_Instrumental {
            get {
                return ResourceManager.GetString("SongSearch_Search_Tags_SongStyle_Instrumental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jazz.
        /// </summary>
        public static string SongSearch_Search_Tags_SongStyle_Jazz {
            get {
                return ResourceManager.GetString("SongSearch_Search_Tags_SongStyle_Jazz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to J-Pop.
        /// </summary>
        public static string SongSearch_Search_Tags_SongStyle_JPop {
            get {
                return ResourceManager.GetString("SongSearch_Search_Tags_SongStyle_JPop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to J-Rock.
        /// </summary>
        public static string SongSearch_Search_Tags_SongStyle_JRock {
            get {
                return ResourceManager.GetString("SongSearch_Search_Tags_SongStyle_JRock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K-Pop.
        /// </summary>
        public static string SongSearch_Search_Tags_SongStyle_KPop {
            get {
                return ResourceManager.GetString("SongSearch_Search_Tags_SongStyle_KPop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metal.
        /// </summary>
        public static string SongSearch_Search_Tags_SongStyle_Metal {
            get {
                return ResourceManager.GetString("SongSearch_Search_Tags_SongStyle_Metal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nightcore.
        /// </summary>
        public static string SongSearch_Search_Tags_SongStyle_Nightcore {
            get {
                return ResourceManager.GetString("SongSearch_Search_Tags_SongStyle_Nightcore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string SongSearch_Search_Tags_SongStyle_None {
            get {
                return ResourceManager.GetString("SongSearch_Search_Tags_SongStyle_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pop.
        /// </summary>
        public static string SongSearch_Search_Tags_SongStyle_Pop {
            get {
                return ResourceManager.GetString("SongSearch_Search_Tags_SongStyle_Pop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punk.
        /// </summary>
        public static string SongSearch_Search_Tags_SongStyle_Punk {
            get {
                return ResourceManager.GetString("SongSearch_Search_Tags_SongStyle_Punk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R&amp;B.
        /// </summary>
        public static string SongSearch_Search_Tags_SongStyle_RB {
            get {
                return ResourceManager.GetString("SongSearch_Search_Tags_SongStyle_RB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rock.
        /// </summary>
        public static string SongSearch_Search_Tags_SongStyle_Rock {
            get {
                return ResourceManager.GetString("SongSearch_Search_Tags_SongStyle_Rock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soul.
        /// </summary>
        public static string SongSearch_Search_Tags_SongStyle_Soul {
            get {
                return ResourceManager.GetString("SongSearch_Search_Tags_SongStyle_Soul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speedcore.
        /// </summary>
        public static string SongSearch_Search_Tags_SongStyle_Speedcore {
            get {
                return ResourceManager.GetString("SongSearch_Search_Tags_SongStyle_Speedcore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swing.
        /// </summary>
        public static string SongSearch_Search_Tags_SongStyle_Swing {
            get {
                return ResourceManager.GetString("SongSearch_Search_Tags_SongStyle_Swing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Techno.
        /// </summary>
        public static string SongSearch_Search_Tags_SongStyle_Techno {
            get {
                return ResourceManager.GetString("SongSearch_Search_Tags_SongStyle_Techno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trance.
        /// </summary>
        public static string SongSearch_Search_Tags_SongStyle_Trance {
            get {
                return ResourceManager.GetString("SongSearch_Search_Tags_SongStyle_Trance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TV &amp; Film.
        /// </summary>
        public static string SongSearch_Search_Tags_SongStyle_TVFilm {
            get {
                return ResourceManager.GetString("SongSearch_Search_Tags_SongStyle_TVFilm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Game.
        /// </summary>
        public static string SongSearch_Search_Tags_SongStyle_VideoGame {
            get {
                return ResourceManager.GetString("SongSearch_Search_Tags_SongStyle_VideoGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vocaloid.
        /// </summary>
        public static string SongSearch_Search_Tags_SongStyle_Vocaloid {
            get {
                return ResourceManager.GetString("SongSearch_Search_Tags_SongStyle_Vocaloid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classical &amp; Orchestral.
        /// </summary>
        public static string SongSearch_Search_Tags_SongStyleClassicalOrchestral {
            get {
                return ResourceManager.GetString("SongSearch_Search_Tags_SongStyleClassicalOrchestral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hip Hop &amp; Rap.
        /// </summary>
        public static string SongSearch_Search_Tags_SongStyleHipHopRap {
            get {
                return ResourceManager.GetString("SongSearch_Search_Tags_SongStyleHipHopRap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kids &amp; Family.
        /// </summary>
        public static string SongSearch_Search_Tags_SongStyleKidsFamily {
            get {
                return ResourceManager.GetString("SongSearch_Search_Tags_SongStyleKidsFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searches for songs.
        /// </summary>
        public static string SongSearch_Search_ToolTip {
            get {
                return ResourceManager.GetString("SongSearch_Search_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter song name, artist, mapper, or bsr key.
        /// </summary>
        public static string SongSearch_Search_Watermark {
            get {
                return ResourceManager.GetString("SongSearch_Search_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist.
        /// </summary>
        public static string Workspace_CustomLevels_ColumnHeader_Artist {
            get {
                return ResourceManager.GetString("Workspace_CustomLevels_ColumnHeader_Artist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BSR.
        /// </summary>
        public static string Workspace_CustomLevels_ColumnHeader_BSR {
            get {
                return ResourceManager.GetString("Workspace_CustomLevels_ColumnHeader_BSR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DL Date.
        /// </summary>
        public static string Workspace_CustomLevels_ColumnHeader_ChangeDate {
            get {
                return ResourceManager.GetString("Workspace_CustomLevels_ColumnHeader_ChangeDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E.
        /// </summary>
        public static string Workspace_CustomLevels_ColumnHeader_E {
            get {
                return ResourceManager.GetString("Workspace_CustomLevels_ColumnHeader_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ex.
        /// </summary>
        public static string Workspace_CustomLevels_ColumnHeader_Ex {
            get {
                return ResourceManager.GetString("Workspace_CustomLevels_ColumnHeader_Ex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ex+.
        /// </summary>
        public static string Workspace_CustomLevels_ColumnHeader_ExPlus {
            get {
                return ResourceManager.GetString("Workspace_CustomLevels_ColumnHeader_ExPlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H.
        /// </summary>
        public static string Workspace_CustomLevels_ColumnHeader_H {
            get {
                return ResourceManager.GetString("Workspace_CustomLevels_ColumnHeader_H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapper.
        /// </summary>
        public static string Workspace_CustomLevels_ColumnHeader_Mapper {
            get {
                return ResourceManager.GetString("Workspace_CustomLevels_ColumnHeader_Mapper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N.
        /// </summary>
        public static string Workspace_CustomLevels_ColumnHeader_N {
            get {
                return ResourceManager.GetString("Workspace_CustomLevels_ColumnHeader_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletes the selected custom level.
        /// </summary>
        public static string Workspace_CustomLevels_Command_Delete {
            get {
                return ResourceManager.GetString("Workspace_CustomLevels_Command_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh the custom level list.
        /// </summary>
        public static string Workspace_CustomLevels_Command_Refresh {
            get {
                return ResourceManager.GetString("Workspace_CustomLevels_Command_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Workspace_CustomLevels_CulumnHeader_Title {
            get {
                return ResourceManager.GetString("Workspace_CustomLevels_CulumnHeader_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist.
        /// </summary>
        public static string Workspace_CustomLevels_Detail_Artist {
            get {
                return ResourceManager.GetString("Workspace_CustomLevels_Detail_Artist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beats per minute.
        /// </summary>
        public static string Workspace_CustomLevels_Detail_BeatsPerMinute {
            get {
                return ResourceManager.GetString("Workspace_CustomLevels_Detail_BeatsPerMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BSR (ID).
        /// </summary>
        public static string Workspace_CustomLevels_Detail_BSR {
            get {
                return ResourceManager.GetString("Workspace_CustomLevels_Detail_BSR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy the bsr key. Can be used to request the map in Twitch..
        /// </summary>
        public static string Workspace_CustomLevels_Detail_Command_CopyBsrKey_Tooltip {
            get {
                return ResourceManager.GetString("Workspace_CustomLevels_Detail_Command_CopyBsrKey_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Workspace_CustomLevels_Detail_Description {
            get {
                return ResourceManager.GetString("Workspace_CustomLevels_Detail_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difficulties.
        /// </summary>
        public static string Workspace_CustomLevels_Detail_Difficulties {
            get {
                return ResourceManager.GetString("Workspace_CustomLevels_Detail_Difficulties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downvotes.
        /// </summary>
        public static string Workspace_CustomLevels_Detail_Downvotes {
            get {
                return ResourceManager.GetString("Workspace_CustomLevels_Detail_Downvotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string Workspace_CustomLevels_Detail_Duration {
            get {
                return ResourceManager.GetString("Workspace_CustomLevels_Detail_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapper.
        /// </summary>
        public static string Workspace_CustomLevels_Detail_Mapper {
            get {
                return ResourceManager.GetString("Workspace_CustomLevels_Detail_Mapper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No description available.
        /// </summary>
        public static string Workspace_CustomLevels_Detail_NoDescription {
            get {
                return ResourceManager.GetString("Workspace_CustomLevels_Detail_NoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualified.
        /// </summary>
        public static string Workspace_CustomLevels_Detail_Qualified {
            get {
                return ResourceManager.GetString("Workspace_CustomLevels_Detail_Qualified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranked.
        /// </summary>
        public static string Workspace_CustomLevels_Detail_Ranked {
            get {
                return ResourceManager.GetString("Workspace_CustomLevels_Detail_Ranked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score.
        /// </summary>
        public static string Workspace_CustomLevels_Detail_Score {
            get {
                return ResourceManager.GetString("Workspace_CustomLevels_Detail_Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seconds.
        /// </summary>
        public static string Workspace_CustomLevels_Detail_Seconds {
            get {
                return ResourceManager.GetString("Workspace_CustomLevels_Detail_Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Workspace_CustomLevels_Detail_SongName {
            get {
                return ResourceManager.GetString("Workspace_CustomLevels_Detail_SongName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtitle.
        /// </summary>
        public static string Workspace_CustomLevels_Detail_SongSubName {
            get {
                return ResourceManager.GetString("Workspace_CustomLevels_Detail_SongSubName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string Workspace_CustomLevels_Detail_Tags {
            get {
                return ResourceManager.GetString("Workspace_CustomLevels_Detail_Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song Detail.
        /// </summary>
        public static string Workspace_CustomLevels_Detail_Title {
            get {
                return ResourceManager.GetString("Workspace_CustomLevels_Detail_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded.
        /// </summary>
        public static string Workspace_CustomLevels_Detail_Uploaded {
            get {
                return ResourceManager.GetString("Workspace_CustomLevels_Detail_Uploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upvotes.
        /// </summary>
        public static string Workspace_CustomLevels_Detail_Upvotes {
            get {
                return ResourceManager.GetString("Workspace_CustomLevels_Detail_Upvotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open path in file explorer.
        /// </summary>
        public static string Workspace_CustomLevels_OpenPathInFileExplorer {
            get {
                return ResourceManager.GetString("Workspace_CustomLevels_OpenPathInFileExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates a playlist containing all custom songs.
        /// </summary>
        public static string Workspace_CustomLevels_SaveToPlaylist {
            get {
                return ResourceManager.GetString("Workspace_CustomLevels_SaveToPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Levels.
        /// </summary>
        public static string Workspace_CustomLevels_Title {
            get {
                return ResourceManager.GetString("Workspace_CustomLevels_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds the song to the selected playlist.
        /// </summary>
        public static string Workspace_Playlist_AddCustomLevel {
            get {
                return ResourceManager.GetString("Workspace_Playlist_AddCustomLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difficulty.
        /// </summary>
        public static string Workspace_Playlist_ColumnHeader_Difficultiy {
            get {
                return ResourceManager.GetString("Workspace_Playlist_ColumnHeader_Difficultiy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetch playlist data from beatsaver.com.
        /// </summary>
        public static string Workspace_Playlist_FetchPlaylistData {
            get {
                return ResourceManager.GetString("Workspace_Playlist_FetchPlaylistData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove song from playlist.
        /// </summary>
        public static string Workspace_Playlist_RemoveSongFromPlaylist_ToolTip {
            get {
                return ResourceManager.GetString("Workspace_Playlist_RemoveSongFromPlaylist_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save playlist with the current song order.
        /// </summary>
        public static string Workspace_Playlist_SavePlaylistWithSongOrder {
            get {
                return ResourceManager.GetString("Workspace_Playlist_SavePlaylistWithSongOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add folder.
        /// </summary>
        public static string Workspace_Playlists_AddFolderCommand {
            get {
                return ResourceManager.GetString("Workspace_Playlists_AddFolderCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add playlist.
        /// </summary>
        public static string Workspace_Playlists_AddPlaylistCommand {
            get {
                return ResourceManager.GetString("Workspace_Playlists_AddPlaylistCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open path in file explorer.
        /// </summary>
        public static string Workspace_Playlists_OpenPathInFileExplorer {
            get {
                return ResourceManager.GetString("Workspace_Playlists_OpenPathInFileExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlists.
        /// </summary>
        public static string Workspace_Playlists_Title {
            get {
                return ResourceManager.GetString("Workspace_Playlists_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new channel.
        /// </summary>
        public static string Workspace_TwitchIntegration_Channels_AddChannel {
            get {
                return ResourceManager.GetString("Workspace_TwitchIntegration_Channels_AddChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the selected channel.
        /// </summary>
        public static string Workspace_TwitchIntegration_Channels_DeleteChannel {
            get {
                return ResourceManager.GetString("Workspace_TwitchIntegration_Channels_DeleteChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitch Channels.
        /// </summary>
        public static string Workspace_TwitchIntegration_Channels_Header {
            get {
                return ResourceManager.GetString("Workspace_TwitchIntegration_Channels_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel Name.
        /// </summary>
        public static string Workspace_TwitchIntegration_Channels_Watermark {
            get {
                return ResourceManager.GetString("Workspace_TwitchIntegration_Channels_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScoreSaber.
        /// </summary>
        public static string Workspace_TwitchIntegration_ScoreSaber_Title {
            get {
                return ResourceManager.GetString("Workspace_TwitchIntegration_ScoreSaber_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to selected playlist.
        /// </summary>
        public static string Workspace_TwitchIntegration_SongHistory_AddToPlaylist {
            get {
                return ResourceManager.GetString("Workspace_TwitchIntegration_SongHistory_AddToPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BSR.
        /// </summary>
        public static string Workspace_TwitchIntegration_SongHistory_ColumnHeader_BSR {
            get {
                return ResourceManager.GetString("Workspace_TwitchIntegration_SongHistory_ColumnHeader_BSR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel.
        /// </summary>
        public static string Workspace_TwitchIntegration_SongHistory_ColumnHeader_Channel {
            get {
                return ResourceManager.GetString("Workspace_TwitchIntegration_SongHistory_ColumnHeader_Channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Song.
        /// </summary>
        public static string Workspace_TwitchIntegration_SongHistory_ColumnHeader_DeleteSong {
            get {
                return ResourceManager.GetString("Workspace_TwitchIntegration_SongHistory_ColumnHeader_DeleteSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapper.
        /// </summary>
        public static string Workspace_TwitchIntegration_SongHistory_ColumnHeader_LevelAuthorName {
            get {
                return ResourceManager.GetString("Workspace_TwitchIntegration_SongHistory_ColumnHeader_LevelAuthorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received At.
        /// </summary>
        public static string Workspace_TwitchIntegration_SongHistory_ColumnHeader_ReceivedAt {
            get {
                return ResourceManager.GetString("Workspace_TwitchIntegration_SongHistory_ColumnHeader_ReceivedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist.
        /// </summary>
        public static string Workspace_TwitchIntegration_SongHistory_ColumnHeader_SongAuthorName {
            get {
                return ResourceManager.GetString("Workspace_TwitchIntegration_SongHistory_ColumnHeader_SongAuthorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Workspace_TwitchIntegration_SongHistory_ColumnHeader_SongName {
            get {
                return ResourceManager.GetString("Workspace_TwitchIntegration_SongHistory_ColumnHeader_SongName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete all received songs.
        /// </summary>
        public static string Workspace_TwitchIntegration_SongHistory_DeleteAllSongs {
            get {
                return ResourceManager.GetString("Workspace_TwitchIntegration_SongHistory_DeleteAllSongs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song History.
        /// </summary>
        public static string Workspace_TwitchIntegration_SongHistory_Header {
            get {
                return ResourceManager.GetString("Workspace_TwitchIntegration_SongHistory_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start auto-adding to selected playlist
        ///Songs will be added to playlist once you stop auto-adding.
        /// </summary>
        public static string Workspace_TwitchIntegration_SongHistory_Start_ToolTip {
            get {
                return ResourceManager.GetString("Workspace_TwitchIntegration_SongHistory_Start_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop auto-add.
        /// </summary>
        public static string Workspace_TwitchIntegration_SongHistory_Stop_ToolTip {
            get {
                return ResourceManager.GetString("Workspace_TwitchIntegration_SongHistory_Stop_ToolTip", resourceCulture);
            }
        }
    }
}
