//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSM.App.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSM.App.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy.
        /// </summary>
        public static string enum_Difficulty_Easy {
            get {
                return ResourceManager.GetString("enum_Difficulty_Easy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expert.
        /// </summary>
        public static string enum_Difficulty_Expert {
            get {
                return ResourceManager.GetString("enum_Difficulty_Expert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExpertPlus.
        /// </summary>
        public static string enum_Difficulty_ExpertPlus {
            get {
                return ResourceManager.GetString("enum_Difficulty_ExpertPlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard.
        /// </summary>
        public static string enum_Difficulty_Hard {
            get {
                return ResourceManager.GetString("enum_Difficulty_Hard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string enum_Difficulty_Normal {
            get {
                return ResourceManager.GetString("enum_Difficulty_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PopUp.
        /// </summary>
        public static string enum_FilterMode_PopUp {
            get {
                return ResourceManager.GetString("enum_FilterMode_PopUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row.
        /// </summary>
        public static string enum_FilterMode_Row {
            get {
                return ResourceManager.GetString("enum_FilterMode_Row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BeatLeader.
        /// </summary>
        public static string enum_LeaderboardType_BeatLeader {
            get {
                return ResourceManager.GetString("enum_LeaderboardType_BeatLeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string enum_LeaderboardType_None {
            get {
                return ResourceManager.GetString("enum_LeaderboardType_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScoreSaber.
        /// </summary>
        public static string enum_LeaderboardType_ScoreSaber {
            get {
                return ResourceManager.GetString("enum_LeaderboardType_ScoreSaber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BeatLeader.
        /// </summary>
        public static string enum_NavigationType_BeatLeaderIntegration {
            get {
                return ResourceManager.GetString("enum_NavigationType_BeatLeaderIntegration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Levels.
        /// </summary>
        public static string enum_NavigationType_CustomLevels {
            get {
                return ResourceManager.GetString("enum_NavigationType_CustomLevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlists.
        /// </summary>
        public static string enum_NavigationType_Playlists {
            get {
                return ResourceManager.GetString("enum_NavigationType_Playlists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScoreSaber.
        /// </summary>
        public static string enum_NavigationType_ScoreSaberIntegration {
            get {
                return ResourceManager.GetString("enum_NavigationType_ScoreSaberIntegration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitch.
        /// </summary>
        public static string enum_NavigationType_TwitchIntegration {
            get {
                return ResourceManager.GetString("enum_NavigationType_TwitchIntegration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BeatLeader.
        /// </summary>
        public static string enum_PlaylistsSourceAvailability_BeatLeader {
            get {
                return ResourceManager.GetString("enum_PlaylistsSourceAvailability_BeatLeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beat Saber Favourites.
        /// </summary>
        public static string enum_PlaylistsSourceAvailability_BeatSaberFavourites {
            get {
                return ResourceManager.GetString("enum_PlaylistsSourceAvailability_BeatSaberFavourites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Levels.
        /// </summary>
        public static string enum_PlaylistsSourceAvailability_CustomLevels {
            get {
                return ResourceManager.GetString("enum_PlaylistsSourceAvailability_CustomLevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string enum_PlaylistsSourceAvailability_None {
            get {
                return ResourceManager.GetString("enum_PlaylistsSourceAvailability_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlists.
        /// </summary>
        public static string enum_PlaylistsSourceAvailability_Playlists {
            get {
                return ResourceManager.GetString("enum_PlaylistsSourceAvailability_Playlists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScoreSaber.
        /// </summary>
        public static string enum_PlaylistsSourceAvailability_ScoreSaber {
            get {
                return ResourceManager.GetString("enum_PlaylistsSourceAvailability_ScoreSaber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song Search.
        /// </summary>
        public static string enum_PlaylistsSourceAvailability_SongSearch {
            get {
                return ResourceManager.GetString("enum_PlaylistsSourceAvailability_SongSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song Suggest.
        /// </summary>
        public static string enum_PlaylistsSourceAvailability_SongSuggest {
            get {
                return ResourceManager.GetString("enum_PlaylistsSourceAvailability_SongSuggest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitch.
        /// </summary>
        public static string enum_PlaylistsSourceAvailability_Twitch {
            get {
                return ResourceManager.GetString("enum_PlaylistsSourceAvailability_Twitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curated.
        /// </summary>
        public static string enum_SearchParamRelevance_Curated {
            get {
                return ResourceManager.GetString("enum_SearchParamRelevance_Curated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest.
        /// </summary>
        public static string enum_SearchParamRelevance_Latest {
            get {
                return ResourceManager.GetString("enum_SearchParamRelevance_Latest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random.
        /// </summary>
        public static string enum_SearchParamRelevance_Random {
            get {
                return ResourceManager.GetString("enum_SearchParamRelevance_Random", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        public static string enum_SearchParamRelevance_Rating {
            get {
                return ResourceManager.GetString("enum_SearchParamRelevance_Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relevance.
        /// </summary>
        public static string enum_SearchParamRelevance_Relevance {
            get {
                return ResourceManager.GetString("enum_SearchParamRelevance_Relevance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom.
        /// </summary>
        public static string enum_SongDetailPosition_Bottom {
            get {
                return ResourceManager.GetString("enum_SongDetailPosition_Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        public static string enum_SongDetailPosition_Right {
            get {
                return ResourceManager.GetString("enum_SongDetailPosition_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contributors.
        /// </summary>
        public static string Info_Contributors {
            get {
                return ResourceManager.GetString("Info_Contributors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Development.
        /// </summary>
        public static string Info_Development {
            get {
                return ResourceManager.GetString("Info_Development", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help with JS and CSS.
        /// </summary>
        public static string Info_HelpWithJSandCSS {
            get {
                return ResourceManager.GetString("Info_HelpWithJSandCSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon.
        /// </summary>
        public static string Info_Icon {
            get {
                return ResourceManager.GetString("Info_Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idea.
        /// </summary>
        public static string Info_Idea {
            get {
                return ResourceManager.GetString("Info_Idea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libraries.
        /// </summary>
        public static string Info_Libraries {
            get {
                return ResourceManager.GetString("Info_Libraries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing.
        /// </summary>
        public static string Info_Testing {
            get {
                return ResourceManager.GetString("Info_Testing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string Playlist_Author {
            get {
                return ResourceManager.GetString("Playlist_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Playlist_Description {
            get {
                return ResourceManager.GetString("Playlist_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Playlist_Title {
            get {
                return ResourceManager.GetString("Playlist_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BeatLeader.
        /// </summary>
        public static string Settings_BeatLeader {
            get {
                return ResourceManager.GetString("Settings_BeatLeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Levels.
        /// </summary>
        public static string Settings_CustomLevels {
            get {
                return ResourceManager.GetString("Settings_CustomLevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string Settings_General {
            get {
                return ResourceManager.GetString("Settings_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlists.
        /// </summary>
        public static string Settings_Playlists {
            get {
                return ResourceManager.GetString("Settings_Playlists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        public static string Settings_Playlists_Available {
            get {
                return ResourceManager.GetString("Settings_Playlists_Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScoreSaber.
        /// </summary>
        public static string Settings_ScoreSaber {
            get {
                return ResourceManager.GetString("Settings_ScoreSaber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        public static string Settings_ScoreSaber_Available {
            get {
                return ResourceManager.GetString("Settings_ScoreSaber_Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song Suggest.
        /// </summary>
        public static string Settings_SongSuggest {
            get {
                return ResourceManager.GetString("Settings_SongSuggest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BeatLeader user id.
        /// </summary>
        public static string Settings_SongSuggest_BLUserId {
            get {
                return ResourceManager.GetString("Settings_SongSuggest_BLUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default leaderboard.
        /// </summary>
        public static string Settings_SongSuggest_DefaultLeaderboard {
            get {
                return ResourceManager.GetString("Settings_SongSuggest_DefaultLeaderboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScoreSaber user id.
        /// </summary>
        public static string Settings_SongSuggest_SSUserId {
            get {
                return ResourceManager.GetString("Settings_SongSuggest_SSUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use BeatLeader leaderboard.
        /// </summary>
        public static string Settings_SongSuggest_UseBLLeaderboard {
            get {
                return ResourceManager.GetString("Settings_SongSuggest_UseBLLeaderboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use ScoreSaber leaderboard.
        /// </summary>
        public static string Settings_SongSuggest_UseSSLeaderboard {
            get {
                return ResourceManager.GetString("Settings_SongSuggest_UseSSLeaderboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difficulties.
        /// </summary>
        public static string Song_Difficulties {
            get {
                return ResourceManager.GetString("Song_Difficulties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapper.
        /// </summary>
        public static string Song_Mapper {
            get {
                return ResourceManager.GetString("Song_Mapper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Song_Title {
            get {
                return ResourceManager.GetString("Song_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to change cover image.
        /// </summary>
        public static string ToolTip_Playlist_ClickToChangeCoverImage {
            get {
                return ResourceManager.GetString("ToolTip_Playlist_ClickToChangeCoverImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetch playlist data.
        /// </summary>
        public static string ToolTip_Playlist_FetchData {
            get {
                return ResourceManager.GetString("ToolTip_Playlist_FetchData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save playlist.
        /// </summary>
        public static string ToolTip_Playlist_SavePlaylist {
            get {
                return ResourceManager.GetString("ToolTip_Playlist_SavePlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply current sort order and save playlist.
        /// </summary>
        public static string ToolTip_Playlist_SavePlaylistWithCurrentOrder {
            get {
                return ResourceManager.GetString("ToolTip_Playlist_SavePlaylistWithCurrentOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove song from playlist.
        /// </summary>
        public static string ToolTip_Song_RemoveFromPlaylist {
            get {
                return ResourceManager.GetString("ToolTip_Song_RemoveFromPlaylist", resourceCulture);
            }
        }
    }
}
