//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSM.App.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSM.App.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy.
        /// </summary>
        public static string enum_Difficulty_Easy {
            get {
                return ResourceManager.GetString("enum_Difficulty_Easy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expert.
        /// </summary>
        public static string enum_Difficulty_Expert {
            get {
                return ResourceManager.GetString("enum_Difficulty_Expert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExpertPlus.
        /// </summary>
        public static string enum_Difficulty_ExpertPlus {
            get {
                return ResourceManager.GetString("enum_Difficulty_ExpertPlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard.
        /// </summary>
        public static string enum_Difficulty_Hard {
            get {
                return ResourceManager.GetString("enum_Difficulty_Hard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string enum_Difficulty_Normal {
            get {
                return ResourceManager.GetString("enum_Difficulty_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BeatLeader.
        /// </summary>
        public static string enum_LeaderboardType_BeatLeader {
            get {
                return ResourceManager.GetString("enum_LeaderboardType_BeatLeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string enum_LeaderboardType_None {
            get {
                return ResourceManager.GetString("enum_LeaderboardType_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScoreSaber.
        /// </summary>
        public static string enum_LeaderboardType_ScoreSaber {
            get {
                return ResourceManager.GetString("enum_LeaderboardType_ScoreSaber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BeatLeader.
        /// </summary>
        public static string enum_NavigationType_BeatLeaderIntegration {
            get {
                return ResourceManager.GetString("enum_NavigationType_BeatLeaderIntegration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Levels.
        /// </summary>
        public static string enum_NavigationType_CustomLevels {
            get {
                return ResourceManager.GetString("enum_NavigationType_CustomLevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlists.
        /// </summary>
        public static string enum_NavigationType_Playlists {
            get {
                return ResourceManager.GetString("enum_NavigationType_Playlists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScoreSaber.
        /// </summary>
        public static string enum_NavigationType_ScoreSaberIntegration {
            get {
                return ResourceManager.GetString("enum_NavigationType_ScoreSaberIntegration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitch.
        /// </summary>
        public static string enum_NavigationType_TwitchIntegration {
            get {
                return ResourceManager.GetString("enum_NavigationType_TwitchIntegration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beat Saber Favourites.
        /// </summary>
        public static string enum_PlaylistsSourceAvailability_BeatSaberFavourites {
            get {
                return ResourceManager.GetString("enum_PlaylistsSourceAvailability_BeatSaberFavourites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Levels.
        /// </summary>
        public static string enum_PlaylistsSourceAvailability_CustomLevels {
            get {
                return ResourceManager.GetString("enum_PlaylistsSourceAvailability_CustomLevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string enum_PlaylistsSourceAvailability_None {
            get {
                return ResourceManager.GetString("enum_PlaylistsSourceAvailability_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlists.
        /// </summary>
        public static string enum_PlaylistsSourceAvailability_Playlists {
            get {
                return ResourceManager.GetString("enum_PlaylistsSourceAvailability_Playlists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song Search.
        /// </summary>
        public static string enum_PlaylistsSourceAvailability_SongSearch {
            get {
                return ResourceManager.GetString("enum_PlaylistsSourceAvailability_SongSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song Suggest.
        /// </summary>
        public static string enum_PlaylistsSourceAvailability_SongSuggest {
            get {
                return ResourceManager.GetString("enum_PlaylistsSourceAvailability_SongSuggest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitch.
        /// </summary>
        public static string enum_PlaylistsSourceAvailability_Twitch {
            get {
                return ResourceManager.GetString("enum_PlaylistsSourceAvailability_Twitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curated.
        /// </summary>
        public static string enum_SearchParamRelevance_Curated {
            get {
                return ResourceManager.GetString("enum_SearchParamRelevance_Curated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest.
        /// </summary>
        public static string enum_SearchParamRelevance_Latest {
            get {
                return ResourceManager.GetString("enum_SearchParamRelevance_Latest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random.
        /// </summary>
        public static string enum_SearchParamRelevance_Random {
            get {
                return ResourceManager.GetString("enum_SearchParamRelevance_Random", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        public static string enum_SearchParamRelevance_Rating {
            get {
                return ResourceManager.GetString("enum_SearchParamRelevance_Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relevance.
        /// </summary>
        public static string enum_SearchParamRelevance_Relevance {
            get {
                return ResourceManager.GetString("enum_SearchParamRelevance_Relevance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom.
        /// </summary>
        public static string enum_SongDetailPosition_Bottom {
            get {
                return ResourceManager.GetString("enum_SongDetailPosition_Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        public static string enum_SongDetailPosition_Right {
            get {
                return ResourceManager.GetString("enum_SongDetailPosition_Right", resourceCulture);
            }
        }
    }
}
